// Editix XML Editor
// https://www.editix.com
// Copyright (c) 2026 Alexandre Brillant
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// See the GNU General Public License for more details: https://www.gnu.org/licenses/gpl-3.0
//
// AI Training Restriction :
// This source code is provided for human use only.
// Using this code to train, fine-tune, or develop AI models,
// machine learning systems, or similar technologies is
// STRICTLY PROHIBITED. Violations will terminate all rights
// under the applicable license.

package com.japisoft.editix.action.file.export;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Properties;

public class JavaMetaClass {
	private String name;
	
	public JavaMetaClass( String name ) {
		this.name = Tools.toClassName( name );
	}

	private Properties p;

	public void setAttribute( String name, String value ) {
		if ( p == null )
			p = new Properties();
		p.setProperty( Tools.convertIfKeyWord( name ), value );
	}

	private ArrayList al = null;

	public void addContentElement( String name ) {
		if ( al == null )
			al = new ArrayList();
		if ( !al.contains( Tools.toClassName( name ) ) )
			al.add( Tools.toClassName( name ) );
	}
		
	private boolean textContent = false;

	public void setText() {
		textContent = true;
	}

	public void write( PrintWriter pw, String pack ) {
		pw.println( "package " + pack + ";" );
		pw.println();
		pw.println( "import java.util.ArrayList;" );
		pw.println();
		pw.println( "/**" );
		pw.println(	"*\tGenerated by EditiX" );
		pw.println( "*\thttp://www.editix.com" );
		pw.println( "*/");
		pw.println( "public class " + name + " extends AbstractElement {" );

		// Attributs
		if ( p != null ) {
			pw.println();
			Enumeration e = p.propertyNames();
			while ( e.hasMoreElements() ) {
				String att = ( String )e.nextElement();
				pw.println( "\tprivate String " + att + ";" );
			}
			pw.println();
			e = p.propertyNames();
			while ( e.hasMoreElements() ) {
				String att = ( String )e.nextElement();
				// Setter
				pw.println( "\tpublic void " + Tools.toSetName( att ) + "( String _value ) {" );
				pw.println( "\t\tthis." + att + " = _value;" );
				pw.println( "\t}" );
				pw.println();
				// Getter
				pw.println( "\tpublic String " + Tools.toGetName( att ) + "() {" );
				pw.println( "\t\treturn " + att + ";" );
				pw.println( "\t}" );
				pw.println();
			}			
		}

		// Content
		if ( al != null ) {
			pw.println();
			for ( int i = 0; i < al.size(); i++ ) {
				String name = ( String )al.get( i );
				pw.println( "\tprivate ArrayList" + " " + name.toLowerCase() + ";" );
			}
			pw.println();
			for ( int i = 0; i < al.size(); i++ ) {
				String name = ( String )al.get( i );
				// Adder
				pw.println( "\tpublic void " + Tools.toAddName( name.toLowerCase() ) + "( " + name + " _value ) {" );
				pw.println( "\t\tif ( " + name.toLowerCase() + "==null ) " + name.toLowerCase() + " = new ArrayList();" );
				pw.println( "\t\tthis." + name.toLowerCase() + ".add( _value );" );
				pw.println( "\t}" );
				pw.println();
				// Getter
				pw.println( "\tpublic " + "ArrayList " + Tools.toGetName( name ) + "() {" );
				pw.println( "\t\treturn " + name.toLowerCase() + ";" );
				pw.println( "\t}" );
				pw.println();
				// Has
				pw.println( "\tpublic " + "boolean " + Tools.toAnyName( "has", name ) + "() {" );
				pw.println( "\t\treturn " + name.toLowerCase() + " != null;" );
				pw.println( "\t}" );
				pw.println();
				// First
				pw.println( "\tpublic " + name + " " + Tools.toAnyName( "getFirst", name ) + "() {" );
				pw.println( "\t\tif ( " + name.toLowerCase() + "!= null && " + name.toLowerCase() + ".size() > 0 ) {" );
				pw.println( "\t\t\treturn (" + name + ")" + name.toLowerCase() + ".get(0);" );
				pw.println( "\t\t} else return null;" );
				pw.println( "\t}" );
				pw.println();
			}
		}
		
		if ( textContent ) {
			pw.println();
			pw.println( "\tprivate String value;" );
			pw.println( "\tpublic void setValue( String value ) {" );
			pw.println( "\t\tthis.value = value;" );
			pw.println( "\t}" );
			pw.println();
			pw.println( "\tpublic String getValue() {" );
			pw.println( "\t\treturn value;" );
			pw.println( "\t}" );
		}
		
		pw.println( "}" );
	}
}
