all:
	javac *.java -d ../../../../../classes -classpath ../../../../../classes:../../../../../lib/fp-parser.jar:../../../../../lib/fp-tool.jar
	cp *.gif ..\..\..\..\..\classes\com\japisoft\xmlpad\tree
